# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue in PhotoMeta Restore! We appreciate your contribution. Our team will review it soon.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors
newPRWelcomeComment: >
  Thank you for submitting your first pull request to PhotoMeta Restore! We're excited to review your contribution.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congratulations on your first merged pull request to PhotoMeta Restore! We appreciate your contribution to making this project better.

# Mark issues/PRs as stale after 60 days of inactivity
stale:
  daysUntilStale: 60
  daysUntilClose: 7
  exemptLabels:
    - pinned
    - security
    - enhancement
  staleLabel: stale
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs within 7 days.
    Thank you for your contributions.
  closeComment: >
    This issue has been automatically closed due to inactivity.
    Please feel free to reopen it if you still believe it's relevant. 